### PR TITLE
Fix alt text on default gray student photos

### LINKED ISSUE #88: Institutions with more than 1 student without a portrait fail to display correct image
This is an example of the portraits working correctly. When a student doesn't have a picture associated with their name, a default gray dude will be provided:
image

When there are 2 or more students without a portrait, the first will receive the default gray guy, and the others will show ugly alt text.
image

### PR DESCRIPTION
**Pull request by DannyOppenheimer**
Close #88

### CODE REVIEW

**Review by AndrewLester — APPROVED** [review]

File: js/scripts.js [hunk 1]
```diff
@@ -322,7 +322,7 @@ function details(institution) {
     studentsList.className = 'students-list';
 
     for (student of institution.students) {
-        var studentPhoto = document.createElement('img'),
+        const studentPhoto = document.createElement('img'),
             studentName = document.createElement('p'),
```
Comment (ErikBoesen) [inline js/scripts.js:326]: nit: fix the indentation of these
